# Based on: https://github.com/errata-ai/Google/blob/master/Google/Periods.yml
extends: existence
message: "Don't use periods with acronyms or initialisms such as '%s'."
link: 'https://docs.mongodb.com/meta/style-guide/style/abbreviations/'
level: error
nonword: true
tokens:
  - '\b(?:[A-Z]\.){3,}'