# Based on: https://github.com/errata-ai/Google/blob/master/Google/Exclamation.yml

extends: existence
message: "Use interjections with care."
link: 'https://docs.mongodb.com/meta/style-guide/writing/use-interjections-with-care/'
nonword: true
level: warning
tokens:
  - '\w!(?:\s|$)'