extends: existence
message: "IPv4 addresses should use periods (.) as separators ('%s')."
link: 'https://docs.mongodb.com/meta/style-guide/style/ip-addresses/'
level: error
nonword: true
tokens:
  - '((((\d{1,3}:){3})(\d{1,3}))(/\d+)?)'