name: Link Checker
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Check out source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install checker tool
        run: go install github.com/terakilobyte/checker@latest

      - name: Run checker tool
        run: git diff --name-only HEAD^..HEAD | tr "\n" "," | xargs checker --changes
